// Re-export all needed icons from lucide-react (unique only - each icon appears exactly once)
export { 
  Award, Users, Settings, LogOut, KeyRound, User, ArrowRight,
  Search, ChevronDown, ChevronUp, ChevronRight, ChevronLeft,
  AlertTriangle, CheckCircle, XCircle, AlertCircle, Info,
  RefreshCw, Clock, Calendar, TrendingUp, Crown,
  Mail, Server, Globe, Shield, Lock, Key, ShieldAlert,
  UserCheck, Download, Sparkles, Loader2, Play,
  Plus, Trash2, Eye, EyeOff, Copy, X,
  HelpCircle, BadgeCheck, BadgeAlert, BadgeInfo, BadgeHelp,
  ShieldOff, LockOpen,
  Fingerprint, Scan,
  UserPlus, UserMinus, UserCog, UserX,
  Building2, Building, Briefcase, Layers,
  Wand2, FunctionSquare, Calculator,
  Database, Braces, Hash, Variable,
  Save, Edit2,
  Beaker, TestTube, FlaskConical, CheckCheck,
  Lightbulb, MessageSquare, ChatBubble,
  AlertOctagon, CircleCheck, CircleX, CircleAlert,
  Sliders, ToggleLeft, ToggleRight,
  ExternalLink, Star, Heart, ThumbsUp, ThumbsDown,
  Flag, FlagOff, Bookmark, BookmarkOff, Pin, PinOff,
  Archive, ArchiveOff, ZoomIn, ZoomOut,
  Sun, Moon, Wifi, Battery, Volume2, Mic, Video, Phone,
  CalendarCheck, CalendarX, CalendarPlus, ClockAlert,
  Timer, Hourglass, Bell, SearchCheck, FilterX,
  ArrowUp, ArrowDown, ArrowLeft, Move,
  Expand, Shrink, Columns, Rows,
  Cloud, Zap, LightbulbOff, CandlestickChart,
  BarChart, BarChart2, BarChart3, BarChart4, LineChart, PieChart,
  Activity, Target, Crosshair, Compass, Map, MapPin,
  Languages, AtSign, Percent, DollarSign,
  Equal,
  PlusCircle, Minus, MinusCircle, Divide, Multiply,
  File, FileCode, FileJson, FileText, Folder, FolderOpen,
  Package, Box, ShoppingBag, ShoppingCart,
  CreditCard, Wallet, Receipt, Ticket,
  SortAsc, SortDesc, Crop, Frame, PanelLeft, PanelRight,
  PanelTop, PanelBottom, Sidebar, Header, Footer, Table
} from 'lucide-react';